# **Theoretical Questions:**


**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

Ans - NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python. Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries solidifies its position as the cornerstone of numerical computing in Python.

**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

Ans - The np. mean() method returns the arithmetic mean, but the np. average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

Ans - As we know Numpy is a general-purpose array-processing package that provides a high-performance multidimensional array object, and tools for working with these arrays. Let’s discuss how can we reverse a Numpy array.

In [1]:
#example
import numpy as np

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# using shortcut method to reverse
res = np.flip(ini_array)

# printing result
print("final array", str(res))


final array [5 4 6 3 2 1]


**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

ANS - We can check the datatype of Numpy array by using dtype. Then it returns the data type all the elements in the array. In the given example below we import NumPy library and craete an array using “array()” method with integer value. Then we store the data type of the array in a variable named “data_type” using the ‘dtype’ attribute, and after then we can finally, we print the data type.

**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

ANS - NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data.

**Some important points about Numpy arrays:**

- We can create an N-dimensional array in Python using Numpy.array().
- The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (Note You can also create a structured array in Python).
- Element-wise operation is possible.
- Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
- Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.

**Comparison between Numpy array and Python List**

- Element Overhead: Lists in Python store additional information about each element, such as its type and reference count. This overhead can be significant when dealing with a large number of elements.

- Datatype: Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.

- Memory Fragmentation: Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.

- Performance: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. They are generally used as general-purpose data structures.

- Functionality: Lists can store any data type, but lack specialized NumPy functions for numerical operations.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

Ans - Advantages of NumPy

Performance: NumPy's array operations are executed at compiled C speed, making them significantly faster than equivalent operations performed using Python lists. This performance boost is vital for handling large datasets and complex computations efficiently.

**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.**

Ans - numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.


Syntax  :  numpy.vstack(tup)


Parameters :

tup   : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the first axis.


Return  : [stacked ndarray] The stacked array of the input arrays.

In [2]:
# Python program explaining
# vstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.


Syntax  :  numpy.hstack(tup)


Parameters :

tup   : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the second axis.


Return  : [stacked ndarray] The stacked array of the input arrays.

In [3]:
# Python program explaining
# hstack() function

import numpy as geek

# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.**

Ans - The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.


**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

Ans - array_split() s plitting into equal or nearly equal sub-arrays or is similar to numpy. split(), but it allows for uneven splitting of arrays. This is useful when the array cannot be evenly divided by the specified number of splits.

**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

Ans - Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

# **Practical Questions:**


**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

Ans -

In [4]:
import numpy as np
random_matrix = np.random.randint(1,100,size=(3,3))
print(random_matrix)

[[51 88 22]
 [53 78 18]
 [10 24 47]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

Ans -

In [7]:
import numpy as np
# 1-D array having elements [1 2 3 4 5 6 7 8 9 1]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

# Now we can convert this 1-D array into 2-D in two ways

# 1. having dimension 2 x 5
arr1 = arr.reshape(2, 5)
print ('After reshaping having dimension 2x5:')
print (arr1)
print ('\n')

# 2. having dimension 5 x 2
arr2 = arr.reshape(5, 2)
print ('After reshaping having dimension 5x2:')
print (arr2)
print ('\n')


After reshaping having dimension 2x5:
[[1 2 3 4 5]
 [6 7 8 9 1]]


After reshaping having dimension 5x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]]




**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

Ans -

In [8]:
import numpy as np
from math import sqrt

#  Element 1
C_1= 3/5
S_1= 4/5
matrix_1 = np.matrix([[C_1**2, C_1*S_1,-C_1**2,-C_1*S_1],[C_1*S_1,S_1**2,-C_1*S_1,-S_1**2],
                    [-C_1**2,-C_1*S_1,C_1**2,C_1*S_1],[-C_1*S_1,-S_1**2,C_1*S_1,S_1**2]])
empty_mat1 = np.zeros((6,6))
empty_mat1[0:4 , 0:4] = empty_mat1[0:4 ,0:4] + matrix_1
#print(empty_mat1)
# Element 2

C_2 = 0
S_2 = 1
matrix_2 = 1.25*np.matrix([[C_2**2, C_2*S_2,-C_2**2,-C_2*S_2],[C_2*S_2,S_2**2,-C_2*S_2,-S_2**2],
                    [-C_2**2,-C_2*S_2,C_2**2,C_2*S_2],[-C_2*S_2,-S_2**2,C_2*S_2,S_2**2]])
empty_mat2 = np.zeros((6,6))
empty_mat2[0:2,0:2] = empty_mat2[0:2,0:2] + matrix_2[0:2,0:2]
empty_mat2[4:6,0:2] = empty_mat2[4:6,0:2] + matrix_2[2:4,0:2]
empty_mat2[0:2,4:6] = empty_mat2[0:2,4:6] + matrix_2[2:4,2:4]
empty_mat2[4:6,4:6] = empty_mat2[4:6,4:6] + matrix_2[0:2,0:2]

print(empty_mat1+empty_mat2)

[[ 0.36  0.48 -0.36 -0.48  0.    0.  ]
 [ 0.48  1.89 -0.48 -0.64  0.    1.25]
 [-0.36 -0.48  0.36  0.48  0.    0.  ]
 [-0.48 -0.64  0.48  0.64  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.   -1.25  0.    0.    0.    1.25]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

Ans -

In [9]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating an array of integers from 10 to 60 using np.arange()
array = np.arange(10, 60)

# Printing a message indicating an array of integers from 10 to 60
print("Array of the integers from 10 to 60")

# Printing the array of integers from 10 to 60
print(array)

Array of the integers from 10 to 60
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

Ans -

In [14]:
# Importing necessary library
import numpy as np

# Creating a NumPy array containing strings
x = np.array(['Python', 'numpy', 'pandas', 'Examples'], dtype=str)

# Displaying the content of the original array
print("\nOriginal Array:")
print(x)

# Checking if each element contains digits only
r1 = np.char.isdigit(x)

# Checking if each element contains lower case letters only
r2 = np.char.islower(x)

# Checking if each element contains upper case letters only
r3 = np.char.isupper(x)

# Displaying results
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)



Original Array:
['Python' 'numpy' 'pandas' 'Examples']
Digits only = [False False False False]
Lower cases only = [False  True  True False]
Upper cases only = [False False False False]


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

Ans -

In [16]:
# Importing necessary library
import numpy as np

# Creating a NumPy array containing strings
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=str)

# Displaying the original array
print("Original Array:")
print(x)

# Using np.char.join to join elements of the array with a space character
r = np.char.join(" ", x)

# Displaying the result after joining elements with a space
print(r)


Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

Ans -

In [17]:
# Importing the NumPy library
import numpy as np

# Displaying a message for addition operation
print("Add:")
# Performing addition
print(np.add(1.0, 4.0))

# Displaying a message for subtraction operation
print("Subtract:")
# Performing subtraction
print(np.subtract(1.0, 4.0))

# Displaying a message for multiplication operation
print("Multiply:")
# Performing multiplication
print(np.multiply(1.0, 4.0))

# Displaying a message for division operation
print("Divide:")
# Performing division
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements**

Ans - This problem involves writing a NumPy program to generate a 5x5 matrix where all elements are initially set to zero, except for the main diagonal, which is filled with the values 1, 2, 3, 4, and 5. The task requires utilizing NumPy's array manipulation capabilities to efficiently construct and modify the matrix, ensuring the specified values are placed correctly on the diagonal. The resulting matrix combines elements of identity matrices with custom diagonal values.

In [18]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a diagonal matrix with diagonal elements 1, 2, 3, 4, 5 using np.diag()
x = np.diag([1, 2, 3, 4, 5])

# Printing the diagonal matrix 'x'
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

Ans -

In [25]:
from numpy import random

x=random.randint(1000, size=(100))

print(x)

[103 769 573 505 871 631 980 129 145 108 104 197 323 674 209 968 759 868
 877 969 163 444  23 366 629 878 195 436 451 951 111 223 178 541 764 575
 380 141 967  45  83 589 537 712 588  59 364 560 433 272 858 269 584 633
  86 792 397 146 802 470 344 147 589 856 564 491 588 733 895 403 324 817
 664 994 406  11 785 388  57 479 175 985 581 169 920 392 186 770 240 786
 203 649 949 715 663 685 913 278 362 863]


In [26]:
for num in range(1,1000):
   if num > 1:
       for i in range(2,num):
           if (num % i) == 0:
               break
       else:
           print(f"{num} is a prime number!")

2 is a prime number!
3 is a prime number!
5 is a prime number!
7 is a prime number!
11 is a prime number!
13 is a prime number!
17 is a prime number!
19 is a prime number!
23 is a prime number!
29 is a prime number!
31 is a prime number!
37 is a prime number!
41 is a prime number!
43 is a prime number!
47 is a prime number!
53 is a prime number!
59 is a prime number!
61 is a prime number!
67 is a prime number!
71 is a prime number!
73 is a prime number!
79 is a prime number!
83 is a prime number!
89 is a prime number!
97 is a prime number!
101 is a prime number!
103 is a prime number!
107 is a prime number!
109 is a prime number!
113 is a prime number!
127 is a prime number!
131 is a prime number!
137 is a prime number!
139 is a prime number!
149 is a prime number!
151 is a prime number!
157 is a prime number!
163 is a prime number!
167 is a prime number!
173 is a prime number!
179 is a prime number!
181 is a prime number!
191 is a prime number!
193 is a prime number!
197 is a prime nu

**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

Ans -

In [38]:
week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

print ("Day" + (" "*12) + "High Temperature")
print ("-"*30)
temperature = []
temp = 0
spaces = 0

for i,x in enumerate(week_days):
    temp_input = input ("Enter the temperature for" +x+str(":"))
    temperature.append(int(temp_input))
    spaces = 15-len(x)
    print (x," "*spaces,temperature[i])

avg= sum(temperature)//len(week_days)


print ("The average temperature for this week is", avg)

Day            High Temperature
------------------------------
Enter the temperature forMonday:37
Monday           37
Enter the temperature forTuesday:38
Tuesday          38
Enter the temperature forWednesday:39
Wednesday        39
Enter the temperature forThursday:40
Thursday         40
Enter the temperature forFriday:41
Friday           41
Enter the temperature forSaturday:42
Saturday         42
Enter the temperature forSunday:43
Sunday           43
The average temperature for this week is 40
